### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support 

### ISSUE THREAD

**Issue by c1a1o1** [dikatok/pix2pix-matting#1]
C:\Users\caocao\Anaconda3\python.exe D:/work/gan-pix2pix/pix2pix-matting-master/pix2pix-matting-master/test.py --image 00001.jpg --graph_filename model.pb --output out.jpg
2018-06-01 13:54:13.423403: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2018-06-01 13:54:14.686859: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 960M major: 5 minor: 0 memoryClockRate(GHz): 1.176
pciBusID: 0000:02:00.0
totalMemory: 4.00GiB freeMemory: 3.34GiB
2018-06-01 13:54:14.687397: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 960M, pci bus id: 0000:02:00.0, compute capability: 5.0)
Traceback (most recent call last):
  File "C:\Users\caocao\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1323, in _do_call
    return fn(*args)
  File "C:\Users\caocao\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1293, in _run_fn
    self._extend_graph()
  File "C:\Users\caocao\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1354, in _extend_graph
    self._session, graph_def.SerializeToString(), status)
  File "C:\Users\caocao\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'Dequantize' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:
  <no registered kernels>

**Comment by 24rochak** [comment]
Heyy, did u solve the issue ??
